version: '3.8'
services:

  seowasil_db_local:
    container_name: seowasil_db_local
    image: postgres
    restart: always # 컨테이너가 종료되면 항상 다시 시작
    ports:
      - "5432:5432"
    env_file:
      - .env.local
    volumes:
      # 명명된 볼륨으로 바꾸는거 고민해봐야 함. 최소 배포환경에선 명명된 볼륨 사용으로. 이유도 같이
      - ./local/db:/var/lib/postgresql/data # 호스트의 ./db 디렉토리를 컨테이너의 /var/lib/postgresql/data 에 마운트
  
